---
title: IIS
description: Outlyer Monitoring Integration for Microsoft's Internet Information Services (IIS) webserver
logo: iis.png
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - webserver
  - microsoft
