---
title: IIS
description: Outlyer Monitoring Integration for Microsoft's Internet Information Services (IIS) webserver
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/iis/resources/iis.png?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  microsoft: iis
  web: iis
