---
title: IIS
description: Outlyer Monitoring Integration for Microsoft's Internet Information Services (IIS) webserver
icon:
  url: https://github.com/outlyerapp/integrations/raw/master/iis/resources/iis.png
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  microsoft: iis
  web: iis
