---
title: etcd
description: Outlyer Monitoring Integration for etcd, the distributed reliable key-value store
logo: etcd.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - configuration
  - containers
