---
title: etcd
description: Outlyer Monitoring Integration for etcd, the distributed reliable key-value store
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/etcd/resources/etcd.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  configuration: etcd
form:
- name: selectors_etcd
  description: "This selector is used by the etcd check for querying status and performance metrics. Select all etcd instances, e.g.: app: etcd"
  prompt: "Select all etcd instances"
  type: labelSelectors
