---
title: etcd
description: Outlyer Monitoring Integration for etcd, the distributed reliable key-value store
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/etcd/resources/etcd.svg?sanitize
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  configuration: etcd
