---
title: AWS EC2
description: Outlyer Monitoring Integration to collect metrics from your AWS EC2 Instances via Cloudwatch
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-ec2/resources/aws-ec2.svg?sanitize=true
version: 1.1.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: ec2