---
title: Tutorial
description: Outlyer Monitoring Tutorial with a collection of tutorial dashboards to introduce new users to Outlyer
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/tutorial/resources/tutorial.svg?sanitize=true
version: 1.0.1
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  outlyer: getting-started