---
title: Tutorial
description: Outlyer Monitoring Tutorial with a collection of tutorial dashboards to introduce new users to Outlyer
icon:
  url: tutorial.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - getting started