---
title: Tutorial
description: A collection of tutorial dashboards to introduce new users to Outlyer
logo: tutorial.svg
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - getting started