---
title: Tomcat
description: Outlyer Monitoring Integration for Tomcat, the popular Servlet and JSP container for Java apps
version: 1.0.0
icon:
  url: tomcat.svg
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - web
  - java