---
title: Tomcat
description: Outlyer Monitoring Integration for Tomcat, the popular Servlet and JSP container for Java apps
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/tomcat/resources/tomcat.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: tomcat
  java: tomcat
form:
- name: selectors_tomcat
  description: "This selector is used by the Tomcat check for querying Tomcat performance metrics via JMX. Select the Tomcat instance, e.g.: app: tomcat"
  prompt: "Select the Tomcat instance"
  type: labelSelectors
- name: tomcat_jmx_port
  description: "Enter the Tomcat JMX port, e.g.: 9012"
  prompt: "Enter the Tomcat JMX port"
  type: string
  required: True
