---
title: Tomcat
description: Outlyer Monitoring Integration for Tomcat, the popular Servlet and JSP container for Java apps
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/tomcat/resources/tomcat.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: tomcat
  java: tomcat