---
title: PostgreSQL
description: Outlyer Monitoring Integration for PostgreSQL, the world's most advanced open source relational database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/postgresql/resources/postgresql.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: postgresql
