---
title: PostgreSQL
description: Outlyer Monitoring Integration for PostgreSQL, the world's most advanced open source relational database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/postgresql/resources/postgresql.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: postgresql
form:
- name: selectors_postgresql
  description: "This selector is used by the PostgreSQL check for querying PostgreSQL status and performance metrics. Select a PostgreSQL instance, e.g.: app: postgresql"
  prompt: "Select a PostgreSQL instance"
  type: labelSelectors
