---
title: AWS Lambda
description: Outlyer Monitoring Integration to collect metrics from your AWS Lambda Functions
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-lambda/resources/aws-lambda.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: lambda
  serverless: lambda