---
title: AWS Lambda
description: Collect metrics to monitor all your AWS Lambda Functions
logo: aws-lambda.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws
  - serverless