---
title: AWS Lambda
description: Outlyer Monitoring Integration to collect metrics from your AWS Lambda Functions
icon:
  url: aws-lambda.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws
  - serverless