
---
title: A test integration
name: test-name
description: An integration to test our integration service
version: 6.2.1
icon:
  url: https://docs2.outlyer.com/assets/img/outlyer-logo-black.svg
labels:
- test
- internal
- integration
