---
title: AWS DynamoDB
description: Outlyer Monitoring Integration to collect metrics from your AWS DynamoDB Tables
logo: aws-dynamodb.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws
  - data-store