---
title: AWS DynamoDB
description: Outlyer Monitoring Integration to collect metrics from your AWS DynamoDB Tables
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-dynamodb/resources/aws-dynamodb.svg?sanitize=true
version: 1.0.0
author:
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: dynamodb
  data-store: dynamodb