---
title: AWS ELB
description: Outlyer Monitoring Integration to collect metrics from your AWS Elastic Load Balancers (ELBs)
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-elb/resources/aws-elb.svg?sanitize=true
version: 1.0.0
author:
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: elb
  load-balancers: elb