---
title: AWS ELB
description: Outlyer Monitoring Integration to collect metrics from your AWS Elastic Load Balancers (ELBs)
icon:
  url: aws-elb.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws
  - load-balancers