---
title: Zookeeper
description: Outlyer Monitoring Integration for Zookeeper, the centralized service for maintaining cluster configuration information
logo: zookeeper.png
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - configuration