---
title: Zookeeper
description: Outlyer Monitoring Integration for Zookeeper, the centralized service for maintaining cluster configuration information
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/zookeeper/resources/zookeeper.svg?sanitize=true
version: 1.0.2
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  configuration: zookeeper
form:
- name: selectors_zookeeper
  description: "This selector is used by the ZooKeeper check for querying ZooKeeper status and performance metrics. Select all ZooKeeper instances, e.g.: app: zookeeper"
  prompt: "Select all ZooKeeper instances"
  type: labelSelectors
