---
title: DNS Check
description: Outlyer Monitoring Integration to monitor the resolvability and lookup times of any DNS entry
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/dns/resources/dns-logo.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: dns
