---
title: DNS Check
description: Outlyer Monitoring Integration to monitor the resolvability and lookup times of any DNS entry
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/dns/resources/dns-logo.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: dns
form:
- name: selectors_dns
  description: "This selector is used by the DNS check to monitor the resolvability of and lookup times for DNS records. Select an instance, e.g.: instance.hostname: <INSTANCE_HERE>"
  prompt: "Select an instance"
  type: labelSelectors
- name: dns_hostname
  description: "The hostname to look up, e.g.: outlyer.com"
  prompt: "The hostname to look up"
  type: string
  required: True
