---
title: Sensu Handler
description: Outlyer Monitoring Integration to collect metrics from Sensu using a Sensu Handler
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/sensu/resources/sensu.svg?sanitize=true
version: 0.9.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  monitoring: sensu
