---
title: HTTP
description: Outlyer Monitoring check to monitor HTTP endpoints and their HTTP response code, response time, and response size
icon:
  url: http.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - http
