---
title: Prometheus
description: Outlyer Monitoring Integration to easily scrape and collect metrics from Prometheus endpoints
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/prometheus/resources/prometheus.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  monitoring: prometheus