---
title: logrotate
description: Outlyer Monitoring Integration for logrotate, the system utility that manages the automatic rotation and compression of log files. 
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/logrotate/resources/logrotate.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
label:
  system: logrotate
