---
title: logrotate
description: Outlyer Monitoring Integration for logrotate, the system utility that manages the automatic rotation and compression of log files. 
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/logrotate/resources/logrotate.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
label:
  system: logrotate
form:
- name: selectors_logrotate
  description: "This selector is used by the logrotate check for querying log files sizes and last rotations. Select all instances that use logrotate, e.g.: instance.hostname: <INSTANCE_HERE>"
  prompt: "Select all instances that use logrotate"
  type: labelSelectors
