---
title: RabbitMQ
description: Outlyer Monitoring Integration for RabbitMQ, the most widely deployed open source message broker
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/rabbitmq/resources/rabbitmq.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  messaging: rabbitmq