---
title: RabbitMQ
description: Outlyer Monitoring Integration for RabbitMQ, the most widely deployed open source message broker
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/rabbitmq/resources/rabbitmq.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  messaging: rabbitmq
form:
- name: selectors_rabbitmq
  description: "This selector is used by the RabbitMQ check for querying RabbitMQ status and performance metrics. Select a RabbitMQ instance, e.g.: app: rabbitmq"
  prompt: "Select a RabbitMQ instance"
  type: labelSelectors
