---
title: RabbitMQ
description: Outlyer Monitoring Integration for RabbitMQ, the most widely deployed open source message broker
logo: rabbitmq.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - messaging