---
title: SSL
description: Outlyer Monitoring Check the checks for the expiration of SSL certificates
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/ssl/resources/ssl.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: ssl
