---
type: "native"
deployments:
  - interval: 10
    selector:
      - outlyer.com/type: 'host'

    service_url: "service:jmx:rmi:///jndi/rmi://localhost:9010/jmxrmi"
    standard_metrics: true

    queries:
      - name: thread_count
        type: gauge
        objectName: "java.lang:type=Threading"
        attributes:
          - name: ThreadCount
