---
title: Apache HTTP Server 2
description: Popular Open source Web Server for hosting web applications
logo: apache2.svg
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - web-server
