---
title: Apache HTTP Server 2
description: Outlyer Monitoring Integration for the Apache 2 HTTP Web Server
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/apache2/resources/apache2.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: apache
