---
title: Apache HTTP Server 2
description: Outlyer Monitoring Integration for the Apache 2 HTTP Web Server
icon:
  url: apache2.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - web-server
