---
title: MongoDB
description: Open source cross-platform document-oriented NoSQL database.
logo: mongodb.svg
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - data-store
