---
title: MongoDB
description: Outlyer Monitorign Integration for MongoDB, the Open source document-oriented NoSQL database
icon:
  url: mongodb.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - data-store
