---
title: Java JMX
description: Outlyer Monitoring Integration for Java applications using JMX
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/java/resources/java.svg?sanitize=true
version: 1.0.1
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  java: jmx
