---
title: Java JMX
description: Outlyer Monitoring Integration for Java applications using JMX
icon:
  url: java.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - java