---
title: Consul
description: Outlyer Monitoring Integration for the Hashicorp Consul service discovery service
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/consul/resources/consul.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  configuration: consul