---
title: Consul
description: Outlyer Monitoring Integration for the Hashicorp Consul service discovery service
icon:
  url: consul.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - configuration