---
title: Elasticsearch
description: Outlyer Monitoring Integration for Elasticsearch, the distributed document store and search engine
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/elasticsearch/resources/elasticsearch.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: elasticsearch 