---
title: Elasticsearch
description: Outlyer Monitoring Integration for Elasticsearch, the distributed document store and search engine
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/elasticsearch/resources/elasticsearch.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: elasticsearch
form:
- name: selectors_elasticsearch
  description: "This selector is used by the Elasticsearch check for querying Elasticsearch status and key metrics. Select all Elasticsearch instances, e.g.: app: elasticsearch"
  prompt: "Select all Elasticsearch instances"
  type: labelSelectors
