---
title: Ping
description: Outlyer Monitoring Check to sends ICMP Ping packets and measure response time
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/ping/resources/ping.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  system: ping
form:
- name: selectors_ping
  description: "This selector is used by the Ping check for querying the instance status and other performance metrics. Select all instances to ping, e.g.: instance.hostname: <INSTANCE_HERE>"
  prompt: "Select all instances to ping"
  type: labelSelectors
