---
title: HAProxy
description: Outlyer Monitoring Integration for HAProxy, the reliable, high-performance load balancer
logo: haproxy.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - load-balancer
