---
title: HAProxy
description: Outlyer Monitoring Integration for HAProxy, the reliable, high-performance load balancer
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/haproxy/resources/haproxy.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: haproxy
  load-balancers: haproxy
