---
title: AWS Kinesis
description: Outlyer Monitoring Integration to collect metrics from your AWS Kinesis Streams
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-kinesis/resources/aws-kinesis.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: kinesis
  messaging: kinesis