---
title: NGinX
description: Outlyer Monitoring Integration for NGinX, the open source web server and proxy
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/nginx/resources/nginx.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  web: nginx
