command: kubernetes-api-server.py
dashboards:
- kubernetes-cluster-overview
description: Monitors the Kubernetes Master Healthz Endpoint
disabled: false
env:
- key: endpoint
  value: healthz
handler: Native
icon: integration--docker
interval: 30
name: kubernetes-api-server-health
plugins:
- kubernetes-api-server.py
selectors: {{.selectors_k8s_api_server}}
timeout: 30
title: 'Kubernetes: API Server Health'
