---
title: AWS RDS
description: Outlyer Monitoring Integration to collect metrics from your AWS RDS Instances
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-rds/resources/aws-rds.svg
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: rds
  data-store: rds