---
title: Kubernetes
description: Outlyer Monitoring Integration for Kubernetes, the container orchestration platform
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/kubernetes/resources/kubernetes.svg?sanitize=true
version: 1.3.2
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  containers: kubernetes
