---
title: Kubernetes
description: Outlyer Monitoring Integration for Kubernetes, the container orchestration platform
icon:
  url: kubernetes.svg
version: 1.3.2
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - containers
