---
title: AWS SNS
description: Collect metrics to monitor all your AWS SNS Topics
logo: aws-sns.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws