---
title: AWS SNS
description: Outlyer Monitoring Integration to collect metrics from your AWS SNS Topics
icon:
  url: aws-sns.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws