---
title: AWS SNS
description: Outlyer Monitoring Integration to collect metrics from your AWS SNS Topics
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-sns/resources/aws-sns.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: sns
form:
- name: selectors_sns
  description: "This selector is used by the AWS SNS check for querying the AWS CloudWatch API. Select an instance, e.g.: instance.hostname: <INSTANCE_HERE>"
  prompt: "Select an instance"
  type: labelSelectors
- name: sns_aws_access_key
  description: "The AWS ACCESS KEY is used by the SNS check for querying the AWS CloudWatch API"
  prompt: "Provide the AWS ACCESS KEY"
  type: string
  required: True
- name: sns_aws_secret_key
  description: "The AWS SECRET KEY is used by the SNS check for querying the AWS CloudWatch API"
  prompt: "Provide the AWS SECRET KEY"
  type: string
  required: True
- name: sns_aws_region
  description: "The AWS REGION is used by the SNS check for querying the AWS CloudWatch API"
  prompt: "Provide the AWS REGION"
  type: string
  required: True
