---
title: AWS S3
description: Outlyer Monitoring Integration to collect metrics from your AWS S3 Buckets
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-s3/resources/aws-s3.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: s3