---
type: "native"
requirements:
  - "mysqlclient==1.3.12"
deployments:
  - interval: 60
    selector:
      - outlyer.com/type: 'host'

    host: 127.0.0.1
    port: 3306
    username: root
    password: mysql
    database: mysql
