---
title: MySQL
description: Outlyer Monitoring Integration for MySQL, the world's most popular open-source relational database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/mysql/resources/mysql.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: mysql
