---
title: MySQL
description: Outlyer Monitoring Integration for MySQL, the world's most popular open-source relational database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/mysql/resources/mysql.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: mysql
form:
- name: selectors_mysql
  description: "This selector is used by the MySQL check for querying MySQL status and performance metrics. Select a MySQL instance, e.g.: app: mysql"
  prompt: "Select a MySQL instance"
  type: labelSelectors
- name: mysql_port
  description: "Enter the port number MySQL is running on"
  prompt: "MySQL Port"
  type: string
  default: "3306"
- name: mysql_username
  description: "Enter the username to connect to MySQL on"
  prompt: "MySQL Username"
  type: string
  default: "root"
- name: mysql_password
  description: "Enter the password to connect to MySQL on"
  prompt: "MySQL Password"
  type: string
  default: "root"