---
title: AWS Billing
description: Outlyer Monitoring Integration to collect metrics from your AWS account Billing to monitor your AWS Costs
icon:
  url: aws-billing.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws