---
title: AWS Billing
description: Outlyer Monitoring Integration to collect metrics from your AWS account Billing to monitor your AWS Costs
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-billing/resources/aws-billing.svg?sanitize=true
version: 1.0.0
author:
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: billing