---
title: AWS Billing
description: Outlyer Monitoring Integration to collect metrics from your AWS account Billing to monitor your AWS Costs
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-billing/resources/aws-billing.svg?sanitize=true
version: 1.0.0
author:
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: billing
form:
- name: selectors_billing
  description: "This selector is used by the AWS Billing check for querying the AWS API. Select an instance, e.g.: instance.hostname: <INSTANCE_HERE>"
  prompt: "Select an instance"
  type: labelSelectors
- name: billing_aws_access_key
  description: "The AWS ACCESS KEY is used by the Billing check for querying the AWS API"
  prompt: "Provide the AWS ACCESS KEY"
  type: labelSelectors
- name: billing_aws_secret_key
  description: "The AWS SECRET KEY is used by the Billing check for querying the AWS API"
  prompt: "Provide the AWS SECRET KEY"
  type: labelSelectors
