---
title: Outlyer Agent
description: Outlyer Monitoring Integration to install the Outlyer Agent and view key agent metrics in your account
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/agent/resources/outlyer-logo-black.svg?sanitize=true
version: 1.0.0
author:
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  outlyer: agent
  system: agent
