---
title: Solr
description: Outlyer Monitoring Integration for Solr, the open source enterprise search platform built on Apache Lucene
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/solr/resources/solr.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  search: solr
form:
- name: selectors_solr
  description: "This selector is used by the Solr check for querying Solr status and key metrics. Select all Solr instances, e.g.: app: solr"
  prompt: "Select all Solr instances"
  type: labelSelectors
