---
title: Cassandra
description: Outlyer Monitoring Integration for the Apache Cassandra NoSQL database
icon:
  url: cassandra.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - data-store
