---
title: Cassandra
description: Outlyer Monitoring Integration for the Apache Cassandra NoSQL database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/cassandra/resources/cassandra.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: cassandra
