---
title: Cassandra
description: Outlyer Monitoring Integration for the Apache Cassandra NoSQL database
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/cassandra/resources/cassandra.svg?sanitize=true
version: 1.0.1
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: cassandra
form:
- name: selectors_cassandra
  description: "This selector is used by the Cassandra check for querying Cassandra status and key metrics. Select all Cassandra instances, e.g.: app: cassandra"
  prompt: "Select all Cassandra instances"
  type: labelSelectors
