---
title: Kafka
description: Outlyer Monitoring Integration for Kafka, the distributed streaming and message queue platform
icon:
  url: kafka.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - messaging
  - java