---
title: Kafka
description: Outlyer Monitoring Integration for Kafka, the distributed streaming and message queue platform
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/kafka/resources/kafka.svg?sanitize=true
version: 1.0.1
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  messaging: kafka
  java: kafka
