---
title: Redis
description: Outlyer Monitoring Integration for Redis, the open source in-memory data store
icon:
  url: redis.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - data-store
