---
title: Redis
description: Outlyer Monitoring Integration for Redis, the open source in-memory data store
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/redis/resources/redis.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  data-store: redis
form:
- name: selectors_redis
  description: "This selector is used by the Redis check for querying Redis status and key metrics. Select all Redis instances, e.g.: app: redis"
  prompt: "Select all Redis instances"
  type: labelSelectors
