---
title: AWS SQS
description: Collect metrics to monitor all your AWS SQS Queues
logo: aws-sqs.svg
version: 1.0.0
author: Outlyer
author-uri: https://www.outlyer.com
license: MIT
categories:
  - aws