---
title: AWS SQS
description: Outlyer Monitoring Integration to collect metrics from your AWS SQS Queues
icon:
  url: https://raw.githubusercontent.com/outlyerapp/integrations/master/aws-sqs/resources/aws-sqs.svg?sanitize=true
version: 1.0.0
author: 
  name: Outlyer
  url: https://www.outlyer.com
license: MIT
labels:
  aws: sqs